# Generated by Django 3.2.6 on 2021-09-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wished_item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
