# Generated by Django 3.2.6 on 2021-09-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210919_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
