# Generated by Django 3.2.6 on 2021-09-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_mywishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyWishlist',
        ),
    ]
